### PR TITLE
simplify navigation from search/explore to taxon page so that back/fo…

### PR DESCRIPTION
**Pull request by jhpoelen**
…rward buttons can be used; for your review @n8upham @JelleZijlstra

Related to https://github.com/mammaldiversity/mammaldiversity.github.io/issues/24 .

The idea to work towards "aspirationally" stable taxon identifiers.  

With this pull request - you'd be redirect to a .../taxon/1235 page from the "explore" pages instead of having some result pop up inside the search result page.

Curious to hear your thoughts,
-jorrit

### CODE REVIEW

**Comment by n8upham** [comment]
This seems to work super well @jhpoelen -- major thanks for pulling this together!  I just did the merge.  

Couple things that we might still think about in this context:
- Are the 'old' permalinks still use-able, and if not, is there a simple way to have those old links redirect to these new pages? I'm think about places like Wikipedia pages and iNaturalist that ideally we would not break existing links to MDD content
- Now that these are per-species pages, this structure would presumably open the possibility for higher taxon pages (genera, families, orders) too, right?  That has been a goal that @JelleZijlstra and @connorjburgin and I have discussed before
- - Higher taxon pages could be populated by separate CSV sheets that would document aspects of taxonomic change above the species level

**Comment by n8upham** [comment]
@jhpoelen Note that I think this change impact the ability to use both "mammaldiversity.org" and "www.mammaldiversity.org" -- with now only the latter working.

Will this be fixed by simply adding a line for "mammaldiversity.org" to the CNAME file?

**Comment by jhpoelen** [comment]
> Will this be fixed by simply adding a line for "mammaldiversity.org" to the CNAME file?

The DNS configuration for mammaldiversity.org needs to change in order to address the www.mammaldiversity.org vs mammaldiversity.org issue #47 .

I'd like to urge you to take ownership of the DNS mammaldiversity.org domain, unless the current administrators fix this issue. Regardless, I think it would be good practice to have more than one person have access to the DNS account just to cover the "hit-by-a-bus" scenario. I've seen many domain become zombie due to silly things like expiration, credit card issues etc.

**Comment by jhpoelen** [comment]
> Are the 'old' permalinks still use-able, and if not, is there a simple way to have those old links redirect to these new pages? I'm think about places like Wikipedia pages and iNaturalist that ideally we would not break existing links to MDD content

Yes, the 'old' permalinks should redirect to the current taxon id landing pages. I am a bit hesitant to use the term "permalink", because even permalinks appear to change quite a bit . . . Note that the redirects are done in javascript, so they work when folks click around in web browsers. More general redirects can be implemented also, and this probably requires setting up a separate server to handle these requests. Not hard to do, but yet another thing to maintain, and something that goes beyond the technical skills needed to maintain mammaldiversity.org via the current GitHub pages / Jekyll combo. 

By the way, you can see the redirect use cases tested here: 

https://github.com/mammaldiversity/mammaldiversity.github.io/blob/master/test/permalink.js

**Comment by jhpoelen** [comment]
> Now that these are per-species pages, this structure would presumably open the possibility for higher taxon pages (genera, families, orders) too, right? That has been a goal that @JelleZijlstra and @connorjburgin and I have discussed before

Yep, pages for higher orders can be generated too. 

some questions:

Did you have a specific identifier scheme in mind to point to higher order taxa? 

How would you imagine keeping the higher order taxonomic information in sync with the existing mdd.csv ? 

Note that ITIS, NCBI and friends, take an approach to list taxa along with their id, label status as well as their  taxonomic parent . 

E.g., 

taxon id | parent taxon id | taxon name | authorship
--- | --- | --- | ---
12345 | 123 | Homo sapiens | L. 1758

However, this relational way to store the data would make it harder for the mdd.csv to be edited in excel.

Another approach would be to introduce taxon ids along with the higher order taxon names in mdd.csv

So, instead of:

id | name | family | order | ...
--- | --- | --- | --- | ---
12345 | Homo sapiens | Hominidae | Primates | ...

you'd introduce identifiers 

id | name | family id | family name | order id | order name | ...
--- | --- | --- | --- | ---
12345 | Homo sapiens | 3456 | Hominidae | 6789 | Primates | ...

This would make it a little easier to edit using excel and find-replace short cuts. And, you can generate higher order taxon pages by grouping taxa by some family and generate some informative landing page.

Curious to hear your, @JelleZijlstra and @connorjburgin thoughts on this.

**Pull request merged**
