### PR TITLE
Rendering improvements

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Apparently the originalNameCombination used to have underscores in it, but it
no longer does, so this code is now broken. Instead, simply italicize the whole
original combination.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
I haven't tested locally yet, let me do that to see if there's any other similar issues.

**Comment by JelleZijlstra** [comment]
OK, confirmed this works.

**Comment by JelleZijlstra** [comment]
Noticed another issue, type specimens were always missing because the name of the column changed. Fixed that too.
Screenshot 2024-07-13 at 1 07 40 PM

**Comment by jhpoelen** [comment]
@JelleZijlstra thanks for your changes to help fix #69 .

Suggest to add unit tests for rending these names similar to https://github.com/mammaldiversity/mammaldiversity.github.io/blob/master/test/permalink.js .

**Comment by n8upham** [comment]
Okay great, thanks @jhpoelen and @JelleZijlstra -- can this pull request be closed thwn based on #69 being merged?

**Comment by jhpoelen** [comment]
@n8upham @JelleZijlstra I believe that there's one fix in #68 that I documented in #71 
 that was not addressed (by design) in #70 .

I prefer to document issues first before fixing them. This may create a little communication overhead, and would allow for incremental pull requests and reviews. I find myself easily overwhelmed by pull requests that include many fixes. 

And, this may be a good opportunity to discuss our collaboration/development workflow, especially because I understand the pleasure of near instant gratification of fixing a bug quickly. 

Curious to hear @n8upham @JelleZijlstra et al. thoughts on all this.

**Comment by JelleZijlstra** [comment]
This PR still fixes a number of issues:

- Fix rendering of type specimen numbers (the category was renamed)
- Render a space around `|` in "nominal names" for aesthetics
- Italicize words between underscores in the original citation
- Fix the explore taxonomy page; it assumed that higher-taxon names were all uppercase which is no longer true

I am not convinced that unit tests like the one in #69 help in a significant way. The bugs we're having are due to changes in the data format and unit tests focused on individual parts of the rendering pipeline can't protect against that. What might be more useful is an integration test that checks against the bundled database.

**Comment by jhpoelen** [comment]
I think adding an integration test is a great idea. As mentioned earlier, the unit tests I introduced help to check assertions on part of the code. And, having a schema check would be a great addition.

Let me know if you need help introducing unit / integration tests.

**Comment by n8upham** [comment]
Hey @jhpoelen , by integration test do you mean a type of automated script that would run (a) within Github (e.g., as an 'action') or (b) outside of Github and offline (e.g., via the jekyll local hosting process)?

If it is the latter, then that might be similar to what I'm currently doing manually -- basically pulling locally, establishing a local host, and checking if links are rendering properly.  The problem with my manual checks is that I have only myself to "confirm" if a page is rendering properly, and don't always have time to do a thorough job.  Glad to hear more ideas about how to improve the efficiency / coherency of now having multiple part-time developers on the MDD project (a great thing!)

**Review by n8upham — APPROVED** [review]
Looks great, thanks!

**Comment by jhpoelen** [comment]
> The problem with my manual checks is that I have only myself to "confirm" if a page is rendering properly, and don't always have time to do a thorough job. Glad to hear more ideas about how to improve the efficiency / coherency of now having multiple part-time developers on the MDD project (a great thing!)

Yes, that is exactly what unit/integration tests are for: to encode assertions into a ever growing suite of integrity checks. This way, folks in a hurry can trust that the test will catch stuff, and for starting folks to gain confidence that their changes are not going to let the MDD castle crumble on their first commit.

There's more benefits to having a test suite. For instance, promoting modular code: modular code is easier to write tests for, and making it easier to make sweeping changes when doing code maintenance or refactoring.

**Pull request merged**
